---
- name: Get number of workers
  shell: >
    oc get nodes --no-headers=true --selector='!node-role.kubernetes.io/master' | wc -l
  register: count_workers

- name: Wait to have all networks allocatable on worker nodes
  shell: >
    oc get nodes --selector='!node-role.kubernetes.io/master' -o jsonpath='{.items[*].status.allocatable}'
  register: nodes_allocation
  until:
    - nodes_allocation.stdout | regex_findall(sriov_network[0].resource) | length == count_workers.stdout | int
    - nodes_allocation.stdout | regex_findall(sriov_network[1].resource) | length == count_workers.stdout | int
  retries: 30
  delay: 30
...
