---
extends: default

rules:
  line-length:
    max: 200
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  braces:
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start: disable

ignore: |
  .github/
  .tools/
  security-audit/
