---

# Label pods - only the labels related to exclude connectivity features are applied, as the
# pods are autodiscovered based on the labels provided in targetpodlabels variable
# in the pipeline

- name: Get pods from example-cnf namespace
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ app_ns }}"
  register: example_cnf_pod_list

# Labels are included after deploying the pods. However, as stated in the certsuite docs:
# "It's highly recommended that the labels should be defined in pod definition rather 
# than added after pod is created"
- name: "Tag pods with autodiscovery labels related to exclude connectivity features in test suites"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: "{{ pod.metadata.name }}"
        namespace: "{{ app_ns }}"
        labels:
          redhat-best-practices-for-k8s.com/skip_connectivity_tests: "true"
          redhat-best-practices-for-k8s.com/skip_multus_connectivity_tests: "true"
  loop: "{{ example_cnf_pod_list.resources }}"
  loop_control:
    loop_var: pod
  when: pod.metadata.name|regex_search(exclude_connectivity_regexp)

...
