---
- name: debug
  debug:
    msg: "this is a debug task"

- name: Create example-cnf facts
  set_fact:
    cnf_namespace: "example-cnf"
    trex_app_first_cr: "{{ trex_app_cr_name | default('trex-app')}}"

- name: Get example-cnf component details from job.components
  set_fact:
    operator_version: "{{ item['version'] }}"
  with_items: "{{ hostvars.localhost.job_info.job.components }}"
  when: item["type"] == "nfv-example-cnf-index"

- name: Find versions from the catalog
  vars:
    catalog_image: "quay.io/rh-nfv-int/nfv-example-cnf-catalog:{{ operator_version }}"
  ansible.builtin.shell:
    cmd: >
      set -e -o pipefail;
      {{ opm_tool_path }} render
      {{ catalog_image }} |
      jq -r '.relatedImages[].image'
  args:
    executable: /bin/bash
  register: catalog_data_cmd
  retries: 1
  delay: 5
  until:
    - catalog_data_cmd.rc == 0

- name: Set trex_app_v from the catalog
  set_fact:
    trex_app_v: "{{ item }}"
  when: '"trex-container-app@" in item'
  loop: "{{ catalog_data_cmd.stdout_lines }}"

- name: "Create leading directories"
  tempfile:
    state: directory
    prefix: example-cnf-launch-trex-job.
  register: cnf_tmp_dir

- name: "Checkout Example CNF deployment role"
  git:
    repo: "https://github.com/rh-nfv-int/nfv-example-cnf-deploy.git"
    dest: "{{ cnf_tmp_dir.path }}/nfv-example-cnf-deploy"
    version: "{{ example_cnf_deploy_script_version|default('master') }}"
    update: true
  register: gitresult

- debug: msg="Git hash is {{ gitresult.after }}"
