---

# Label pods - only the labels related to exclude connectivity features are applied, as the
# pods are autodiscovered based on the labels provided in tnf_targetpodlabels variable
# in the pipeline

- name: Get pods from example-cnf namespace
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ app_ns }}"
  register: example_cnf_pod_list

# Labels are included after deploying the pods. However, as stated here:
# https://github.com/test-network-function/cnf-certification-test#targetpodlabels
# "It's highly recommended that the labels should be defined in pod definition rather 
# than added after pod is created"
- name: "Tag pods with autodiscovery labels related to exclude connectivity features in test suites"
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: "{{ pod.metadata.name }}"
        namespace: "{{ app_ns }}"
        labels:
          test-network-function.com/skip_connectivity_tests: "true"
          test-network-function.com/skip_multus_connectivity_tests: "true"
  loop: "{{ example_cnf_pod_list.resources }}"
  loop_control:
    loop_var: pod
  when: pod.metadata.name|regex_search(exclude_connectivity_regexp)

# if replica = 1, recommended not to set maxUnavailable to 0 or 0% and minAvailable to 100%
# https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/adding-pod-disruption-budgets.md#limitations-on-pod-disruption-budgets
- name: Create PodDisruptionBudget for controller-manager pods
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: List
      items:
        - apiVersion: policy/v1
          kind: PodDisruptionBudget
          metadata:
            name: controller-manager-pdb-min
            namespace: "{{ app_ns }}"
          spec:
            minAvailable: 0
            selector:
              matchLabels:
                control-plane: controller-manager
        - apiVersion: policy/v1
          kind: PodDisruptionBudget
          metadata:
            name: controller-manager-pdb-max
            namespace: "{{ app_ns }}"
          spec:
            maxUnavailable: 1
            selector:
              matchLabels:
                control-plane: controller-manager
...
