---

# Label pods / WIP

- name: Get pods from example-cnf namespace
  k8s_info:
    api_version: v1
    kind: pod
    namespace: "{{ app_ns }}"
  register: example_cnf_pod_list

# In this case and the following, labels are included after deploying the pods. However, as stated here:
# https://github.com/test-network-function/test-network-function#targetpodlabels
# "It's highly recommended that the labels should be defined in pod definition rather than added after pod is created"
- name: Tag pods with autodiscover labels to execute test suites
  shell: |
    set -ex
    oc label pod -n "{{ app_ns }}" "{{ item.metadata.name }}" "{{ app_ns }}"/"{{ targetpodlabels_name }}"="{{ targetpodlabels_value }}" --overwrite
    oc annotate pod -n "{{ app_ns }}" "{{ item.metadata.name }}" test-network-function.com/container_tests="[\"PRIVILEGED_POD\",\"PRIVILEGED_ROLE\"]" --overwrite
  when: item.metadata.name|regex_search(cnfs_regexp)
  loop: "{{ example_cnf_pod_list.resources }}"

- name: Tag pods with autodiscover labels related to exclude connectivity features in test suites
  shell: |
    set -ex
    oc label pod -n "{{ app_ns }}" "{{ item.metadata.name }}" test-network-function.com/skip_connectivity_tests=true --overwrite
  when:  item.metadata.name|regex_search(exclude_connectivity_regexp)
  loop: "{{ example_cnf_pod_list.resources }}"

# Label operators / TODO

...
