---

# Remove labels from pods - only the labels related to exclude connectivity features that are
# currently present (because they may have been deleted because the pod has been restarted,
# so we cannot rely on example_cnf_pod_list)

- name: Get pods from example-cnf namespace that have autodiscovery label defined
  k8s_info:
    api_version: v1
    kind: pod
    namespace: "{{ app_ns }}"
    label_selectors:
      - test-network-function.com/skip_connectivity_tests = true
  register: example_cnf_labelled_pod_list

- name: Remove autodiscovery labels related to exclude connectivity features from the corresponding pods
  shell: |
    set -ex
    {{ app_agent_dir.path }}/oc label pod -n "{{ app_ns }}" "{{ item.metadata.name }}" test-network-function.com/skip_connectivity_tests-
  when: example_cnf_labelled_pod_list.resources|length > 0
  loop: "{{ example_cnf_labelled_pod_list.resources }}"

# Remove labels/annotations from operators

- name: Remove autodiscovery labels/annotations from CSVs
  shell: |
    set -ex
    
    {{ app_agent_dir.path }}/oc label csv -n "{{ app_ns }}" "{{ item.metadata.name }}" test-network-function.com/operator-
    {{ app_agent_dir.path }}/oc annotate csv -n "{{ app_ns }}" "{{ item.metadata.name }}" test-network-function.com/operator_tests-
    {{ app_agent_dir.path }}/oc annotate csv -n "{{ app_ns }}" "{{ item.metadata.name }}" test-network-function.com/subscription_name-
  when: item.metadata.name|regex_search(operators_regexp)
  loop: "{{ example_cnf_csv_list.resources }}"

...
