---

# Remove labels from pods - only the labels related to exclude connectivity features

- name: Remove autodiscovery labels related to exclude connectivity features from pods
  shell: |
    set -ex
    oc label pod -n "{{ app_ns }}" "{{ item.metadata.name }}" test-network-function.com/skip_connectivity_tests-
  when:  item.metadata.name|regex_search(exclude_connectivity_regexp)
  loop: "{{ example_cnf_pod_list.resources }}"

# Remove labels/annotations from operators

- name: Remove autodiscovery labels/annotations from CSVs
  shell: |
    set -ex
    
    oc label csv -n "{{ app_ns }}" "{{ item.metadata.name }}" test-network-function.com/operator-
    oc annotate csv -n "{{ app_ns }}" "{{ item.metadata.name }}" test-network-function.com/operator_tests-
    oc annotate csv -n "{{ app_ns }}" "{{ item.metadata.name }}" test-network-function.com/subscription_name-
  when: item.metadata.name|regex_search(operators_regexp)
  loop: "{{ example_cnf_csv_list.resources }}"

...
