---

- name: Create example-cnf facts
  set_fact:
    cnf_app_networks:
      - name: intel-numa0-net1
        count: 2
    packet_generator_networks:
      - name: intel-numa0-net2
        count: 2
    cnf_namespace: "example-cnf"

- name: Get example-cnf component details from job.components
  set_fact:
    operator_version: "{{ item['version'] }}"
    example_cnf_index_image: "{{ item['data']['url'] }}:{{ item['version'] }}"
    operator_component_id: "{{ item['id'] }}"
  with_items: "{{ hostvars.localhost.job_info.job.components }}"
  when: item["type"] == "nfv-example-cnf-index"

- name: Check example-cnf change presence
  block:
    - name: Check if example-cnf is part of the change
      stat:
        path: "{{ dci_change_dir }}/example-cnf"
      register: examplecnf_change_dir

    - block:
        - name: Generate versions
          shell: 'JSON=$(ls ../example-cnf-[0-9]*.json); if [ -z "$JSON" ]; then JSON=../github.json; fi; ./generate-versions.sh {{ job_logs.path }}/versions.cfg pr$(jq -r .number $JSON).$(jq -r .head.sha $JSON|cut -c1-8)'
          args:
            executable: /bin/bash
            chdir: "{{ dci_change_dir }}/example-cnf"

        - name: Get index version
          shell: ". {{ job_logs.path }}/versions.cfg && echo v${VERSIONS[nfv-example-cnf-index]}"
          register: index_output
          args:
            executable: /bin/bash
            chdir: "{{ dci_change_dir }}/example-cnf"

        - name: Override index and app variables
          set_fact:
            operator_version: "{{ index_output.stdout }}"
            example_cnf_index_image: "quay.io/rh-nfv-int/nfv-example-cnf-catalog:{{ index_output.stdout }}"

        - name: 'Remove  component from the job'
          dci_job_component:
            component_id: "{{ operator_component_id }}"
            job_id: " {{ job_id }} "
            state: absent

      when: examplecnf_change_dir.stat.exists and examplecnf_change_dir.stat.isdir

    - name: Check if nfv-example-cnf-deploy is part of the change
      stat:
        path: "{{ dci_change_dir }}/nfv-example-cnf-deploy"
      register: deploy_change_dir

    - name: Override the deploy_dir variable
      set_fact:
        deploy_dir: "{{ dci_change_dir }}/nfv-example-cnf-deploy"
      when: deploy_change_dir.stat.exists and deploy_change_dir.stat.isdir
  when:
    - dci_change_dir is defined

- name: Create the preflight_operators_to_certify variable
  when:
    - certify_operators | default(false) | bool
    - example_cnf_index_image is defined
  block:
    - name: Get Catalog Data
      ansible.builtin.shell:
        cmd: >
          set -e -o pipefail;
          {{ opm_tool_path }} render
          {{ example_cnf_index_image }} |
          jq -r '.relatedImages[].image'
      args:
        executable: /bin/bash
      register: catalog_data_cmd
      retries: 1
      delay: 5
      until:
        - catalog_data_cmd.rc == 0

    - name: Create an empty preflight_operators_to_certify variable
      ansible.builtin.set_fact:
        preflight_operators_to_certify: []

    - name: Populate the preflight_operators_to_certify variable
      ansible.builtin.set_fact:
        preflight_operators_to_certify: "{{ preflight_operators_to_certify + [dict(bundle_image=item, index_image=example_cnf_index_image)] }}"
      when: '"bundle@" in item'
      loop: "{{ catalog_data_cmd.stdout_lines }}"

    - name: Display the prefight_operators_to_certify variable
      ansible.builtin.debug:
        msg: "{{ preflight_operators_to_certify }}"

- name: "Create CNF Namespace"
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ cnf_namespace }}"
        labels:
          security.openshift.io/scc.podSecurityLabelSync: "false"
          pod-security.kubernetes.io/enforce: "privileged"
          pod-security.kubernetes.io/enforce-version: "latest"

- name: "Add CNF Namespace to the list of NS to get logs from"
  set_fact:
    ns_list: "{{ ns_list|default([]) + [ cnf_namespace ] }}"

- name: Create ResourceQuotas for namespace
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/resource_quota.yml.j2') | from_yaml }}"

- name: Create SRIOV Policies and networks
  ansible.builtin.include_role:
    name: redhatci.ocp.sriov_config
  vars:
    sriov_config_file: "{{ example_cnf_sriov_file }}"

- name: "Install required rpm packages"
  package:
    name:
      - git
      - make
      - python3-openshift
      - python3-pyyaml
      - ansible-collection-community-kubernetes
    state: latest
  become: true

- block:
    - name: Checkout Example CNF deployment roles
      git:
        repo: "https://github.com/rh-nfv-int/nfv-example-cnf-deploy.git"
        dest: "{{ dci_config_dir }}/hooks/{{ cluster_name }}/nfv-example-cnf-deploy"
        version: "{{ example_cnf_deploy_script_version|default('master') }}"
        update: true
      register: gitresult

    - debug: msg="Git hash is {{ gitresult.after }}"

    - name: Set the deploy_dir variable
      set_fact:
        deploy_dir: "{{ dci_config_dir }}/hooks/{{ cluster_name }}/nfv-example-cnf-deploy"

  when:
    - deploy_dir is not defined


- name: Mirror catalog in disconnected environment
  include_tasks: mirror-catalog.yml
  when:
    - dci_disconnected | default(false) | bool

- name: Deploy NFV Example CNF catalog
  include_role:
    name: "{{ deploy_dir }}/roles/example-cnf-catalog"

...
