---
name: lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint -c .yamllint.yml .

  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"

      - name: Install ansible-lint
        run: |
          pip install --upgrade pip
          pip install ansible-lint

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r collections/requirements.yml

      - name: Run ansible-lint
        run: |
          ansible-lint --version
          ansible-lint --profile basic \
            cnfapp/hooks/ \
            draining_validation/hooks/ \
            launch_trex_job/hooks/ \
            preflight/hooks/ \
            upgrade_validation/hooks/
